# Generated by Django 3.2.4 on 2021-06-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0002_auto_20210629_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer_info',
            name='personerity_pick_1',
            field=models.CharField(choices=[('1', '시간 엄수'), ('2', '소통'), ('3', '친화력'), ('4', '협업'), ('5', '아이디어'), ('6', '기획'), ('7', '노력'), ('8', '인내'), ('9', '열정')], max_length=1),
        ),
        migrations.AlterField(
            model_name='designer_info',
            name='personerity_pick_2',
            field=models.CharField(choices=[('1', '시간 엄수'), ('2', '소통'), ('3', '친화력'), ('4', '협업'), ('5', '아이디어'), ('6', '기획'), ('7', '노력'), ('8', '인내'), ('9', '열정')], max_length=1),
        ),
        migrations.AlterField(
            model_name='designer_info',
            name='personerity_pick_3',
            field=models.CharField(choices=[('1', '시간 엄수'), ('2', '소통'), ('3', '친화력'), ('4', '협업'), ('5', '아이디어'), ('6', '기획'), ('7', '노력'), ('8', '인내'), ('9', '열정')], max_length=1),
        ),
    ]
