# Generated by Django 3.2.4 on 2021-06-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0003_auto_20210629_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer_info',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
