# Generated by Django 3.2.4 on 2021-06-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0005_rename_intruduce_designer_info_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer_info',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
