# Generated by Django 3.2.4 on 2021-06-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0007_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
