# Generated by Django 3.2.4 on 2021-06-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designers', '0009_portfolio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('logo', '로고 디자인'), ('package', '패키지 디자인'), ('product', '제품 디자인'), ('web', '웹 디자인'), ('app', '앱 디자인'), ('charatcer', '캐릭터 디자인')], max_length=9, null=True)),
                ('budget', models.IntegerField()),
                ('contest_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('contest_last_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_last_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('contest_references', models.FileField(null=True, upload_to='project/references')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enterprise_id', models.ForeignKey(db_column='enterprise_id', on_delete=django.db.models.deletion.CASCADE, related_name='enterprise', to='clients.enterprise')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(help_text='프로젝트에 관해 궁금한 내용을 물어보세요.')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='apply.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proto_type', models.FileField(null=True, upload_to='apply/prototypes')),
                ('cover_photo', models.ImageField(null=True, upload_to='covers')),
                ('apply_comment', models.CharField(help_text='저의 시안을 소개합니다!', max_length=300)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('applier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('designer_id', models.ForeignKey(db_column='designer_id', on_delete=django.db.models.deletion.CASCADE, related_name='Designer', to='designers.designer_info')),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='apply.project')),
            ],
            options={
                'db_table': 'Apply',
            },
        ),
    ]
