# Generated by Django 3.2.4 on 2021-06-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='기관명', max_length=40)),
                ('certification_number', models.CharField(help_text='인증번호', max_length=10)),
                ('representation', models.CharField(help_text='대표자명', max_length=10)),
                ('social_type', models.CharField(help_text='사회적목적 실현 유형', max_length=20)),
                ('certification_date', models.DateField(help_text='인증시기', null=True)),
                ('location', models.CharField(help_text='소재지', max_length=50)),
                ('tel', models.CharField(help_text='대표번호', max_length=20)),
                ('fax', models.CharField(help_text='팩스번호', max_length=20)),
                ('business_inform', models.CharField(help_text='사업내용', max_length=50)),
                ('service_category', models.CharField(help_text='사회서비스 분야', max_length=50)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('email', models.EmailField(help_text='이메일', max_length=128)),
                ('page', models.URLField(help_text='기업 페이지')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
